AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Cloud Resume Challenge Backend

Globals:
  Function:
    Timeout: 5
    Runtime: python3.12

Resources:

  VisitorTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: cloud-resume-visitors
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

  VisitorApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: cloud-resume-api
      StageName: prod
      Cors:
        AllowMethods: "'GET'"
        AllowHeaders: "'Content-Type'"
        AllowOrigin: "'*'"

  VisitorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: cloud-resume-visitor-counter
      CodeUri: src/
      Handler: lambda_function.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref VisitorTable
      Environment:
        Variables:
          TABLE_NAME: !Ref VisitorTable
      Events:
        GetVisitors:
          Type: Api
          Properties:
            Path: /visitors
            Method: get
            RestApiId: !Ref VisitorApi

Outputs:
  ApiUrl:
    Value: !Sub "https://${VisitorApi}.execute-api.${AWS::Region}.amazonaws.com/prod/visitors"
    Export:
      Name: CloudResumeApiUrl
